### ISSUE TITLE
Plot/Series Selector Clear/Refresh Button

### ISSUE THREAD

**Issue by sreeder** [ODM2/ODMToolsPython#10]
There needs to be some sort of clear and/or refresh button for plotting and series selection. Perhaps this is what the "refresh" button in the Date Time menu is for, but it is not functioning.

For example, when a new filter is applied and series are selected, it plots them as multiple time series. To remove a series from the plot, the user needs to apply the proper filter and then de-select it. This particular issue might be addressed by a new table or frame that allows the user to toggle plotted series on and off.

I notice that that program slows and gets buggy after repeated series selection/de-selection (and sometimes just using a Simple Filter). Some sort of reset functionality might overcome this.

https://hydroserver.codeplex.com/workitem/10181

**Comment by sreeder** [comment]
@AmberSJones  ready for testing on branch btn_refresh

**Comment by AmberSJones** [comment]
The functionality is great. However, the button needs some work. 
 1. The text is cropped.
 2. Let's change the label to "Clear Plot".
 3. We need to move the button- right now it just kind of floats out there. Can we either right align it or else put it immediately to the right of the "Advanced Filter" radio button?
![image](https://cloud.githubusercontent.com/assets/5023186/19286239/28eaf54c-8fba-11e6-9e1c-186090a9861b.png)

**Comment by sreeder** [comment]
@AmberSJones  ready for testing again

**Comment by AmberSJones** [comment]
Excelente!
