### ISSUE TITLE
X11 Moved in OSX 10 - Killed ODM Tools

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODMToolsPython#198]
FYI - a bunch of my python stuff had quit working on my Mac when I upgraded to Yosemite.  The X11 installation was moved from /usr/X11 to /opt/X11.  So, I had to run the following to get things going again:

sudo ln -s /opt/X11 /usr/X11

ODM Tools didn't work after the upgrade until I did this.  This had implications for existing installations and potential future ones.

**Comment by AmberSJones** [comment]
@horsburgh we are not experiencing any issues with this with our upgraded OSX. Should we close?

**Comment by horsburgh** [comment]
I haven't had any issues with this in the latest versions I've been testing, so I'm closing.
