### ISSUE TITLE
Button to Fill Gaps with -9999 values

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#201]
The technicians have requested a button that would insert -9999 into gaps that have been identified by the gap filter. I don't know that this HAS to be done, but we should discuss it when we're prioritizing feature requests.

**Comment by sreeder** [comment]
@AmberSJones This is ready for testing on the nodvfill branch. the gui is a rough sketch, needs a little work before it is done.

**Comment by AmberSJones** [comment]
I cannot get any series to plot using this branch?
![image](https://cloud.githubusercontent.com/assets/5023186/19288127/d384193c-8fc1-11e6-8d21-679711d6cbca.png)

![image](https://cloud.githubusercontent.com/assets/5023186/19288152/eec836b0-8fc1-11e6-8376-7fd9b2c09be3.png)

**Comment by sreeder** [comment]
what version of pandas are you using? there was some code that was deprecated so I tried to fix it. but it looks like I may have done that too soon.

**Comment by sreeder** [comment]
@AmberSJones  reverted to deprecated version until we are ready update the library requirements

**Comment by AmberSJones** [comment]
This is looking good, but I think the form needs a little work. Let's add the text:
"This function fills any gaps less than the gap duration with a no-data value at the fill frequency." 
Change the labels to be "Gap Duration:" and "Fill Frequency:"
Also, the fields on the form need to be lined up.
![image](https://cloud.githubusercontent.com/assets/5023186/19291925/93b6a59a-8fd5-11e6-8db8-1e087177cd45.png)

Furthermore- looks like the units that it is using to fill the gaps are off. i.e., I try to fill with 15 minute data and it fills every 15 hours.

**Comment by sreeder** [comment]
@AmberSJones  ready for testing

**Comment by AmberSJones** [comment]
Ok- seems to be working well. Needs a couple tweaks to the form:
 - Needs a period at the end.
 - Should be 'more' rather than 'less'. (that was my fault)

Note that the correct points appear to have been created at the correct intervals, etc., but the table doesn't function as expected with sorting by ValueID or by LocalDateTime.

**Comment by sreeder** [comment]
@AmberSJones  the form is ready for testing again. In what way is it not behaving as expected?

**Comment by AmberSJones** [comment]
The form is great. 

Re. the table- I assumed that sorting by ValueID would bring the 'nan' of the newly-added points to the top (or bottom) of the table. LocalDateTime seems ok- not sure what I was referring to.
