### ISSUE TITLE
Scripting of save_as and save_existing doesn't write the line that sets the variable

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODMToolsPython#211]
When I do a save_as or save_existing, I get the following code in the script editor:

new_qcl = series_service.get_qcl_by_id(1)
new_method = series_service.get_method_by_id(62)
edit_service.save_existing(new_variable, new_method, new_qcl)

It would seem that this is missing the following line:

new_variable = series_service.get_variable_by_id(35)

The variable "new_variable" needs to be set before it can be used in the save_existing function.

**Comment by sreeder** [comment]
This issue has been addressed in commit c7380a55c272413e3e5a208f931dc58425bf78ec

**Comment by AmberSJones** [comment]
This appears to be addressed. Closing.
