### ISSUE TITLE
ODMTools Optimize Check List

### ISSUE THREAD

**Issue by jmeline** [ODM2/ODMToolsPython#212]
***
Optimizations in ODMTools Check List - **Last updated on Jan 19**
***

- [x] **Pandas**
    - [x] Filter Points
        - [x] Value Threshold
        - [x] Date Filter
        - [x] Value Change Threshold
        - [x] Data Gaps
    - [x] Change Value
        - [x] Add
        - [x] Subtract
        - [x] Multiply
        - [x] Set To
    - [x] Restore Series
    - [x] Restore Selection
    - [x] Linear Drift
    - [x] Interpolate
    - [x] Flag
    - [x] Add Point
    - [x] Lasso Select
    - [x] Delete Point

***

- [ ] **Matplotlib**
    - [ ] Figure out the issue with spines
    - [x] Fix an issue where some heavy functions are called multiple times causing the program to slow down

***

- [ ] **Multiprocessing / Multithreading**
    - [x] Use multithreading techniques to optimize the creation of each individual plot ( Probability, Box Whisker, and Summary)
    - [ ] Optimize startup of ODMTools
    - [x] Optimize editing a plot

***

- [x] Issues
    - [x] Change Value
        - [x] Changed values remain selected
    - [x] FrmFlagValues
        - [x] Not closing correctly when selecting an existing qualifier, so no flag is being assigned
    - [x] DataTable
        - [x] Can't select value from DataTable
        - [x] Not scrolling to view selected points 

***
- [ ] Optimizing
    - [x] Box Whisker (Now seeing 16,750% increase in performance. 335 seconds to 0.2 seconds for 244,000 series)
    - [x] Memory Database
    - [x] Summary
    - [x] DataTable ( FastObjectListView loads 10,000 in 0.1 seconds, Virtual loads on demand and handles millions)
        - [x] Change fastobjectlistview to virtualobjectlistview
        - [x] Implement column sorting on Virtualobjectlistview
        - [x] Select points from graph translate into selected points on the datatable
        

***
- [ ] Testing
    - [x] Test on Mac
        - [x] Work out issue with plotting histograms on Mac ( Must use Pandas 0.15 < )

**Comment by AmberSJones** [comment]
Closing this issue. @sreeder is going to add new issues for the uncompleted aspects.
