### ISSUE TITLE
Unable to Add Points using the Upload CSV

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#224]
This is on the new optimization version. I am unable to add points using the upload CSV functionality. I have tried csv files that had worked with the previous version of the software, and I've also tried to create  a new csv using the template. It looks like several windows flash briefly, but then nothing happens. There is nothing reported in the cmd window.

**Comment by AmberSJones** [comment]
I'm experiencing this same behavior.

**Comment by denvaar** [comment]
I've added some updates to the optimization branch, it's ready to be tested again.

**Comment by AmberSJones** [comment]
I've pulled and tested and am experiencing the same issues... Sorry I missed you today, @denvaar . Will you be in tomorrow (Fri)?

**Comment by AmberSJones** [comment]
@denvaar and I learned more re. the cause of this issue today: if a file is edited on an operating system and used on the same operating system, it works fine. If edited on Mac and loaded in Windows, there are ^M as line breaks in the file.

**Comment by AmberSJones** [comment]
Success! Closing.
