### ISSUE TITLE
Interpolate not giving proper values

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#229]
I interpolated some points that were previously equal to -9999. The points are selected in the screen shot below, which shows their values after interpolation. The values are incorrect ~4.24 should be ~7.

![image](https://cloud.githubusercontent.com/assets/5023186/7357800/5a26280e-ecee-11e4-91e2-5e315a5a2d61.png)

**Comment by sreeder** [comment]
@AmberSJones  were these -9999 previously in the dataset or did you add them using our  add point form?

**Comment by AmberSJones** [comment]
I'm pretty sure that these points were previously in the dataset.

**Comment by sreeder** [comment]
@AmberSJones, I had an idea what was causing this but since I was not able to fully replicate I can't test my fix. If you could try it out and let me know if it works for you now I would appreciate it.

**Comment by AmberSJones** [comment]
I'm not experiencing this error anymore, so I'm closing... hope we don't encounter it again.
