### ISSUE TITLE
LabSampleCode error in the AddPoint form

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#233]
@denvaar and I finally isolated the issue with adding points from a csv and the tool worked for me. However, the LabSampleCode is giving a warning flag (red X) for the uploaded NULL values. If I go in and edit the value and set to NULL, the error goes away. I'm wondering if this also has to do with the line break character as it is the last field in a line.

![image](https://cloud.githubusercontent.com/assets/5023186/7541766/e122ec82-f574-11e4-834b-2a182a346642.png)

**Comment by denvaar** [comment]
Amber, can you check if there is an extra space character in front of the NULL values. As I have been updating some things, I've found that sometimes there was a hidden space before NULL.

**Comment by AmberSJones** [comment]
I don't see any extra space in the file that I was using.

**Comment by AmberSJones** [comment]
Resolved by @denvaar
