### ISSUE TITLE
Columns in Series Selector and in Data Table

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#234]
We discussed changing the order and viewing for columns in the series selector and the data table.

Columns most important for viewing in the Data Table: DataValue, LocalDateTime, QualifierCode

In the Series Selector, we need to make the QC information more on the left of the table to make them more visible.

**Comment by sreeder** [comment]
this will resolve issue #202 as well

**Comment by sreeder** [comment]
ready for testing in branch olvcols

**Comment by AmberSJones** [comment]
Looks good to me.
