### ISSUE TITLE
View point specifics when Filter Window is open

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODMToolsPython#237]
When the Filter Points window is open while editing a series, you can't hover or click on the data points to view the date specifics.  It would be nice to allow both hovering and clicking while the filter window is open.

**Comment by sreeder** [comment]
We need to take this out of Modal mode, this will allow users to select the main window while the filter window is still open

**Comment by sreeder** [comment]
test on branch fix_filters

**Comment by AmberSJones** [comment]
Looks good! Closing.
