### ISSUE TITLE
Start and end date default set in Filter Points

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODMToolsPython#238]
When opening the Filter Points window, the start and end dates under the Date tab are set by default to the current date.  It would be helpful if the start date was set to the beginning of the series and end date set to the end of the series.

**Comment by AmberSJones** [comment]
I've experienced it where the dates of the filter set to the begin/end dates of the series, but also where they don't:
![image](https://cloud.githubusercontent.com/assets/5023186/15338260/61a0cf84-1c3c-11e6-8833-e32bb9f301c3.png)

**Comment by AmberSJones** [comment]
In Windows, it displays the current date time. In Mac, it displays 12/31/2000. On both, if you click 'Clear Filter', it resets to the expected- the Begin and End date times of the series.

**Comment by sreeder** [comment]
test on branch filter_date

**Comment by AmberSJones** [comment]
Looks great on both Mac and Windows. Closing.
