### ISSUE TITLE
Manually changing the date in the Filter Points window

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODMToolsPython#239]
When in the Filter Points window, the dates can only be changed when using the calendar feature.  It would be helpful if the dates could manually be changed.  The program wont let you do this because it thinks you are inputting a date that is outside the series range.

**Comment by AmberSJones** [comment]
Need to test in Windows and Mac.

**Comment by AmberSJones** [comment]
I think this is still an issue, but I can't test until issue #238 is resolved, so I'll add it to that milestone.

**Comment by AmberSJones** [comment]
Looks great. Closing.
