### ISSUE TITLE
Updated edited plot not displayed when opening and executing previous script

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODMToolsPython#240]
After making edits to a specific series, the script was saved.  Next, the series was closed (un-check the series box without closing ODM Tools), then the same series was again checked and re-opened to do further edits.  The previously saved script was opened and executed, yet the plot was not displaying the edited series, but rather the original series as if I had made no edits. 

*Note: This issue had no effect when I closed ODM Tools , re-opened ODM Tools, and executed previously saved script.  The plot was correct.  The issue only arises when you keep ODM Tools open.

![image](https://cloud.githubusercontent.com/assets/12566275/8862523/42a466f6-314e-11e5-98b0-d1a0fff3da9f.png)

**Comment by AmberSJones** [comment]
I think this has been addressed in release 1.2.3. @PhilSuiter , let us know if the behavior for starting/stopping editing is not as expected.
