### ISSUE TITLE
Edit functions do not work for added points

### ISSUE THREAD

**Issue by PhilSuiter** [ODM2/ODMToolsPython#243]
I added several new points by using the csv template and by manually adding a few rows.  These points were displayed in the plot.  The points could be selected, but the 'Change Value, Interpolate, Linear Drift, Flag, and Delete Point' edit functions had no effect on the added points.  Cannot designate flag when adding points. Upon saving there is a datatype conversion problem. The added points contain a string that needs to be converted to an int.

**Comment by sreeder** [comment]
@AmberSJones  this should be ready for testing

**Comment by PhilSuiter** [comment]
I added points and the edit functions still do not change the added
points.  I am pretty sure I installed the latest ODM Tools as well.  Here
is the screenshot
[image: Inline image 1]

**Comment by PhilSuiter** [comment]
I added points and the edit functions still do not change the added points.  Maybe I didn't install the latest ODM Tools?

**Comment by sreeder** [comment]
@PhilSuiter 
The updated code will not be in the installer yet. It is still in the source code under the master branch. if you don't have an environment set up I might be able to get something set up for you. just let me know. 
Thanks

**Comment by AmberSJones** [comment]
Ok- I finally got around to testing this and it is resolved. One outstanding question- added points do not show up in the Table. Is this functionality that we lost when we moved to the new Table that isn't interactive? If so, then don't worry about it and close the issue. 

Can we create a new install ASAP to send out to the techs and others using the software?

**Comment by PhilSuiter** [comment]
All the edit functions work for the added points EXCEPT delete points.  Also, the delete points function will  NOT work for any and all points within the series.

**Comment by sreeder** [comment]
@PhilSuiter this has now been addressed in the source code, i am currently making a new installer it should be posted in the next few minutes

**Comment by PhilSuiter** [comment]
It looks good. I couldn't find any issues

**Comment by AmberSJones** [comment]
This has been addressed. Closing.
