### ISSUE TITLE
Entire database is inaccessible while saving is occurring

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#248]
When one series is being saved, the entire database to which that series belongs is inaccessible. The desired behavior is that only that series would be locked for editing.

**Comment by sreeder** [comment]
the database is still accessible but trying to pull 100,000 values while trying to save 100,000 values really taxes the server so both of the queries slow down significantly. However, if the user editing a series pulls the data BEFORE the 2nd user tries to save the data, the editing should work as normal.

**Comment by AmberSJones** [comment]
We discussed on 6/8/16 and determined that our best route forward is to try to educate users about the limitations of the database at this point. To address this, we would need the database to be more responsive to large queries run simultaneously over the network- this would probably involve adding some indices to the databases or similarly complex database changes. Closing the issue at this point.
