### ISSUE TITLE
Prompt to save script

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#250]
It would be very helpful and prevent the loss of work by prompting to save the script when the program is closed. This has been requested by technicians.

**Comment by sreeder** [comment]
@AmberSJones  ready for testing on savedialog branch

**Comment by AmberSJones** [comment]
This is working, but needs a few tweaks:
1. The dialog is missing a "?"
2. If the user clicks "Yes", then the dialog for saving the script should appear.

**Comment by AmberSJones** [comment]
Addressed.
