### ISSUE TITLE
Add Flag doesn't work when no qualifiers in database

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#253]
When there are no qualifiers in the database, the Add Flag button doesn't work at all. It should prompt for the creation of a new qualifier.

**Comment by AmberSJones** [comment]
I'm synced with the Add Flag branch and still experiencing the same behavior with this issue.

![image](https://cloud.githubusercontent.com/assets/5023186/12582419/410e8f6c-c3fa-11e5-90c6-4590bde887a2.png)

**Comment by sreeder** [comment]
ready for testing on flag_issue branch

**Comment by AmberSJones** [comment]
Ok. This issue has been addressed, but it is on the Beta_1.2.4 branch. @sreeder I'll wait to close the issue until you get the correct branch merged in.

**Comment by sreeder** [comment]
@AmberSJones  I would normally merge this issue into Beta_1.2.4. so it is in the correct location.
