### ISSUE TITLE
SQL Driver Version

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#255]
We need to figure out which SQLServer Driver Version to use: 10.0 or 11.0 or we need to add a test to the code. Currently, the code uses 10.0, but if a user (ahem, me) has 11.0, then it is unable to connect to a SQLServer database. See https://github.com/ODM2/ODMToolsPython/blob/append_save/odmtools/odmservices/service_manager.py

**Comment by sreeder** [comment]
this was addressed by Denver in the ODM2API repository and I copied it over to our code. it should be merged into master in the next few days.

**Comment by AmberSJones** [comment]
I think this is addressed. Closing.
