### ISSUE TITLE
Lasso widget disabled

### ISSUE THREAD

**Issue by fl0f** [ODM2/ODMToolsPython#259]
As I start an Edit session, Lasso widget should be activated by function "editSeries" in odmtools/gui/mnuPlotToolbar.py. In fact it is not the case and I cannot figure out why ? 

If I activate it at application startup : "__init__" function in odmtools/gui/mnuPlotToolbar.py => self.select_tool.Enable(True), Lasso tool is enabled and works properly during first Edit session. As I close Edit session, widget is disabled ("stopEdit" function) and never re-enabled by "editSeries" as it should be.

Thank you for helping

**Comment by fl0f** [comment]
I work on linux 64bit platform

**Comment by sreeder** [comment]
@fl0f  Thank you for reporting this issue. Sorry its taken us so long to get working on it! I believe I have been able to fix this issue (I have not however, fully tested it on a linux machine) the fix should be merged into the master branch of our code in the next few days. If you continue to have issue please let me know and I will gladly take another look at it.

**Comment by AmberSJones** [comment]
I have tested this on Mac and it appears to be addressed. I will close this issue- @fl0f , please re-open or create a new issue if the issue persists for you.
