### ISSUE TITLE
Editing not working correctly during a second session

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODMToolsPython#264]
After the following occurs, editing stops working correctly:
1. I open an edit session on a series and make some changes
2. I save my edits
3. I stop editing
4. I start editing again
5. I make some edits (they are not drawn correctly). If I do an interpolation, the interpolated points and the original points are still drawn on the plot.
6. I save my edits (they are not saved)
7. I stop editing (the series is the same as it was before).
We suspect that this has something to do with the series not being correctly selected and/or the check box not being handled correctly after the first editing session.

**Comment by AmberSJones** [comment]
This sounds similar to issues that @PhilSuiter has reported- after editing and saving and then trying to work on the series again, nothing quite works correctly.

**Comment by AmberSJones** [comment]
Ready for testing in the 1.2.3 release.

**Comment by AmberSJones** [comment]
This is addressed. I can follow @horsburgh 's steps and the behavior is as expected.
