### ISSUE TITLE
Release on Windows

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#272]
The current release (1.2.3) is not installing on Windows. See below for the screenshot:
![image](https://cloud.githubusercontent.com/assets/5023186/15336505/224d4d7e-1c34-11e6-9c2f-65bccfd8aeac.png)

**Comment by sreeder** [comment]
@AmberSJones  the "no-install" is working right?

**Comment by sreeder** [comment]
The install of the program actually still works. The shortcuts however, are pointing to the wrong path. To use, navigate to ProgramFiles/ODMTools and run ODMTools.exe. This issue will be fixed in the next release

**Comment by AmberSJones** [comment]
Yes, the no install is working. I'll wait to close this until testing the new release.
