### ISSUE TITLE
Saving is duplicating data

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#274]
When saving, the series is duplicating points in the data series. This is observed with in the plot and the table. Sometimes there are higher value counts in the series catalog table, though this doesn't seem to be consistent. I have observed it with save and save as existing with both overwrite and append options. When using save as new series, a new series is created with double the points as the original series.

![image](https://cloud.githubusercontent.com/assets/5023186/15341550/82e5d288-1c4c-11e6-8b6e-6c2f9bd66ed5.png)

**Comment by AmberSJones** [comment]
I have been testing this on Mac and cannot replicate it with the 1.2.4 release. I still need to test on Windows, but I am about ready to close it. So, I have not observed the case where the entire data series gets replicated. But I have encountered a case where a single point is being replicated. This is using Append Save. I can't remember if I chose new/old for points overlapping, but i suspect that there was one overlapping point. Here are the commands run:

edit_service.filter_date(datetime.datetime(2015, 5, 1, 0, 0), datetime.datetime(2000, 12, 31, 0, 0))
edit_service.delete_points()
new_qcl = series_service.get_qcl_by_id(1)
new_variable = series_service.get_variable_by_id(53)
new_method = series_service.get_method_by_id(52)
edit_service.save_appending(new_variable, new_method, new_qcl, True)

And here is the overlapping point:
![image](https://cloud.githubusercontent.com/assets/5023186/15593884/70224ac8-236d-11e6-811c-3cf6cd55188f.png)

**Comment by AmberSJones** [comment]
Update: I am still seeing the original behavior (entire series is replicated by saving) on MySQL but not on SQLServer. That may help focus the troubleshooting @sreeder ?

**Comment by sreeder** [comment]
@AmberSJones Thank you for this research it helped me to recreate the issue, and our case is being caused by a permissions error!! the user does not have permission to delete values! so it isn't, but the save is still happening.

**Comment by AmberSJones** [comment]
Update on the single point replication. This occurs on both Windows on Mac. It occurs for Append to Existing for both Keep New and Keep Original options. It ONLY occurs for a single overlapping data point. Behavior is as expected when there are 2 or more overlapping data points.

**Comment by sreeder** [comment]
test on save_issue branch

**Comment by AmberSJones** [comment]
The overlapping single point issue is addressed. It appears that saving no longer creates duplicates on MySQL. Closing.
