### ISSUE TITLE
After editing series is stuck in memory

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#283]
After an editing session, a series is saved. At this point, the checkbox for plotting is unchecked (should remain checked). When editing is toggled off, the series remains plotted as a series for editing. Another series is selected for editing (e.g., the original series). When edits are performed, they occur on the series that is stuck in memory somehow rather than on the series for which the editing should be occurring.

**Comment by sreeder** [comment]
@AmberSJones: the issue doesn't occur on every subsequent editing session right? Just every other one?

**Comment by AmberSJones** [comment]
I haven't seen a pattern. Sometimes it does and sometimes it doesn't! But, it might be every other one.

**Comment by sreeder** [comment]
@AmberSJones where were you testing this at ( which branch or release?)

**Comment by sreeder** [comment]
@AmberSJones I believe the code that addreses this went missing from the master branch, this has been reimplemented in the save_issue branch

**Comment by AmberSJones** [comment]
I think this is addressed. Closing.
