### ISSUE TITLE
Append to Existing- Prepend?

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#289]
Currently, saving using the append to existing option assumes that data are only being appended to the end of a data series. However, what about the option of prepending data to the beginning of an existing data series? Do we want to support that option? If not, should we add a warning that data may be lost.

**Comment by sreeder** [comment]
per our meeting: add a line of text next to append "Add values to the end of a series"

**Comment by sreeder** [comment]
@AmberSJones  ready for testing on branch appendtext

**Comment by AmberSJones** [comment]
Great- just needs some minor adjustments. Should read: Append to Series (adds values to the end of a series)

![image](https://cloud.githubusercontent.com/assets/5023186/19287838/a312328a-8fc0-11e6-938d-652057d3b50e.png)

**Comment by sreeder** [comment]
@AmberSJones  ready to test again

**Comment by AmberSJones** [comment]
Great.
