### ISSUE TITLE
Drift Correction with "No Data Values" 

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#290]
A user has reported an issue when trying to perform drift correction over a period when no data values are included. They report that the no data values are shifted with the drift correction- even when the no data values were *not* selected by the lasso or the filter. The expected behavior is that the no data values should not shift in value (i.e., they should remain -9999), however, the drift correction must account for the spacing of those data values in making the adjustment of all past points. 

@PhilSuiter will you please test this issue? When you perform a drift correction that includes sections of -9999 values, what happens to the -9999 values? Try two cases: 1. those values are selected with the rest of the data and 2. those values are not selected for performing the drift correction.

**Comment by sreeder** [comment]
@AmberSJones  ready for testing on lineardrift branch

**Comment by AmberSJones** [comment]
So, this is working well when the -9999 values are selected with surrounding data points. However, when the lasso is used to select a group of points that encompass some -9999 points (but the -9999 are not selected), the drift correction is not performed at all- no shift is made.
![image](https://cloud.githubusercontent.com/assets/5023186/19287625/b9419d12-8fbf-11e6-8f41-4f9fb45b2483.png)
![image](https://cloud.githubusercontent.com/assets/5023186/19287641/c96092f2-8fbf-11e6-950b-dd27382fcd48.png)

**Comment by sreeder** [comment]
I believe this is happening because it has technically become 2 separate selections, and we only allow a user to do a drift correction when they have a single grouping of points selected. so we need to add some sort of message to indicate this is happening.

**Comment by AmberSJones** [comment]
We determined that we need a message to clarify this behavior. Let me know if/when that is ready.

**Comment by sreeder** [comment]
@AmberSJones  Message has been added

**Comment by AmberSJones** [comment]
Looks good.
