### ISSUE TITLE
Filter on Series Selector not working

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#294]
The filter on the series selector is not working. It says that the database is not loaded, however, series can still be selected and plotted when not using the filter.
![image](https://cloud.githubusercontent.com/assets/5023186/18692040/c44f27b8-7f54-11e6-8c06-a061d7fb02ab.png)

**Comment by sreeder** [comment]
@AmberSJones  Ready for testing on branch simplefilter

**Comment by AmberSJones** [comment]
This is addressed.
