### ISSUE TITLE
Save Dialog Needs to Include Changing Source

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#315]
When saving as a new series, the user can select variable, method, and quality control level. We need to be able to set the source as well.

**Comment by sreeder** [comment]
ready for testing on saveSource branch

**Comment by AmberSJones** [comment]
A few things:

1. We need some indication of which fields are required to create a new source. Maybe just stars next to the field in the form? Also, the error message when fields are not complete should be more specific. How about "All required fields must be completed."?
![image](https://cloud.githubusercontent.com/assets/5023186/23960792/872bb0f0-096e-11e7-9e75-be6e72b1279d.png)

2. It appears to not actually be saving when creating a new source:
![image](https://cloud.githubusercontent.com/assets/5023186/23960846/b267b94e-096e-11e7-987b-afe81fe1b736.png)

**Comment by AmberSJones** [comment]
The above issues are addressed. The only outstanding concern- when I try to select "Metadata" from the dropdown, there is nothing available to select. This does not prevent the saving of the series with the new method, but we should probably address it before pushing these changes.

**Comment by AmberSJones** [comment]
@sreeder ^^^^ this is what is outstanding to be completed before I can approve the associated pull request. Otherwise, I think it's good to go.

**Comment by sreeder** [comment]
@AmberSJones the Metadata ID should be populated from the ISO metadata table which does not have to be populated. Do we need to create a new form to allow the user to create ISO metadata?

**Comment by AmberSJones** [comment]
I think populate it form what exists even if it is empty. It's awkward to have it be blank- I think even selecting NULL would be preferable.

**Comment by sreeder** [comment]
@AmberSJones  this is ready for testing in the saveSource branch

**Comment by AmberSJones** [comment]
@sreeder I'm trying to test this on the saveSource branch. I am unable to plot any series. I've tried with a few different databases. Hopefully this screenshot helps:
![image](https://user-images.githubusercontent.com/5023186/27691894-9a38d650-5ca2-11e7-9fcd-a0f79fba7191.png)

**Comment by AmberSJones** [comment]
Ok, previous issue resolved. However, I am unable to save a new source because NULL is not allowed for metadata ID. I think in the dropdown for Metadata, we need a selection based on the existing, available metadata- perhaps a concatenation of the MetadataID and Title.

![image](https://user-images.githubusercontent.com/5023186/27735838-c026a59c-5d5e-11e7-8c48-9d19a3ac9710.png)

**Comment by AmberSJones** [comment]
Ok, this is resolved. Let's merge and push changes to the release. Should it be a new release?
