### ISSUE TITLE
Error with source when save existing-append

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#316]
I edit some data and then save it using the Append to Series option. The existing series and the data that I have been editing have different Sources. The data that are saved retain their original Source rather than adopting the Source of the existing series. I think that the other metadata behave as expected and adopt the value of the existing series (I have only tested Method, however). It appears that the data were saved as a separate series. It appears that when using save existing-overwrite, the behavior is as expected for source.

**Comment by sreeder** [comment]
@AmberSJones  ready for testing on saveSource branch

**Comment by AmberSJones** [comment]
Same issue occurring here as with saving with new source: 
![image](https://cloud.githubusercontent.com/assets/5023186/23968156/4dc3712c-0987-11e7-84f1-1009a2527e31.png)

**Comment by AmberSJones** [comment]
This looks good.
