### ISSUE TITLE
Unable to Save as New when Issues with some Methods

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODMToolsPython#326]
In some cases, save as new fails when trying to select an existing method. We anticipate that this is related to a character encoding issue in the method description.

**Comment by AmberSJones** [comment]
@sreeder worked to address this in the "methods" branch.

**Comment by AmberSJones** [comment]
I'm testing and still having problems, though different. The save summary populates, but the method is saved as a new method and duplicates the existing method rather than using the existing method.

**Comment by sreeder** [comment]
@AmberSJones is this issue occurring for all series or just the ones we were having previous issues with.

**Comment by AmberSJones** [comment]
Just the ones we were having previous issues with, though I haven't tested extensively with all series.

**Comment by sreeder** [comment]
@AmberSJones  is there a test database with a similar method that I could test on? I don't want to test on the production database.

**Comment by AmberSJones** [comment]
This is functioning properly on the test/qc database but issues persist on the production database.

**Comment by AmberSJones** [comment]
This is addressed on the methods branch. I've tested and it checks out. Let's push it to a release.
